import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Styles from "../styles/internals.module.css";

import { Header, Footer, Dishe, PageTemplate, Search, Character } from '@/components';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>OnFood</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageTemplate>
        <div className={Styles.content}>
          <h1>Encontre opções em Delivery próximos a você.</h1>
          <Search />
          <h2>Descubra seu novo Delivery favorito. Milhares de opções	a um clique.</h2>
          <Character />
        </div>
      </PageTemplate>      
    </>
  );
}

export default Home